# Generated by Django 4.0 on 2021-12-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_nominative', models.CharField(max_length=32, verbose_name='Название')),
                ('case_dative', models.CharField(max_length=32, verbose_name='Дательный падеж')),
                ('tasks_number', models.SmallIntegerField(default=0, verbose_name='Количество заданий в варианте')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['id'],
            },
        ),
    ]
