# Generated by Django 4.0 on 2022-01-01 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reshuffle', '0002_alter_subjects_tasks_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.SmallIntegerField(verbose_name='Номер задания в тесте')),
                ('text', models.TextField(blank=True, verbose_name='Текст задания')),
                ('latex', models.TextField(blank=True, verbose_name='Формула (LaTeX)')),
                ('image', models.ImageField(blank=True, upload_to='thumbnails_task/', verbose_name='Изображение')),
                ('subject_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reshuffle.subjects', verbose_name='Ключ предмета')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст ответа')),
                ('latex', models.TextField(blank=True, verbose_name='Формула (LaTeX)')),
                ('image', models.ImageField(blank=True, upload_to='thumbnails_option/', verbose_name='Изображение')),
                ('is_answer', models.BooleanField(default=False, verbose_name='Верный ответ?')),
                ('task_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reshuffle.tasks', verbose_name='Ключ задания')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
    ]
