# Generated by Django 4.0 on 2022-01-21 18:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import reshuffle.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reshuffle', '0003_tasks_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='options',
            options={'ordering': ['task_fk', 'id'], 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['subject_fk', 'num'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterField(
            model_name='options',
            name='latex',
            field=reshuffle.fields.LatexField(blank=True, verbose_name='Формула (LaTeX)'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='latex',
            field=reshuffle.fields.LatexField(blank=True, verbose_name='Формула (LaTeX)'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='num',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер задания в тесте'),
        ),
        migrations.CreateModel(
            name='SubjAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Ключ группы')),
                ('subject_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reshuffle.subjects', verbose_name='Ключ предмета')),
            ],
            options={
                'verbose_name': 'Право доступа группы к предмету',
                'verbose_name_plural': 'Права доступа групп к предметам',
                'ordering': ['group_id'],
            },
        ),
    ]
