# Generated by Django 4.0 on 2022-01-23 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reshuffle', '0004_alter_options_options_alter_tasks_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjaccess',
            options={'ordering': ['group_id'], 'verbose_name': 'Право доступа группы к предмету', 'verbose_name_plural': 'Права доступа'},
        ),
        migrations.CreateModel(
            name='ArchiveLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('archive_info', models.CharField(max_length=255, verbose_name='Архив')),
                ('action', models.CharField(max_length=255, verbose_name='Действие')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал действий',
                'verbose_name_plural': 'Журнал действий',
                'ordering': ['action_time', 'username'],
            },
        ),
    ]
