# Generated by Django 4.0 on 2022-03-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reshuffle', '0005_alter_subjaccess_options_archivelogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivelogs',
            options={'ordering': ['-action_time'], 'verbose_name': 'Элемент журнала', 'verbose_name_plural': '[#5] Журнал действий'},
        ),
        migrations.AlterModelOptions(
            name='options',
            options={'ordering': ['task_fk', 'id'], 'verbose_name': 'Вариант ответа', 'verbose_name_plural': '[#2] Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='subjaccess',
            options={'ordering': ['group_id'], 'verbose_name': 'Право доступа к каталогу', 'verbose_name_plural': '[#4] Права доступа к каталогу'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'ordering': ['id'], 'verbose_name': 'Предмет', 'verbose_name_plural': '[#3] Предметы'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['subject_fk', 'num'], 'verbose_name': 'Задание', 'verbose_name_plural': '[#1] Задания'},
        ),
        migrations.AddField(
            model_name='subjects',
            name='header',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='parts',
            field=models.JSONField(null=True),
        ),
    ]
