# Generated by Django 4.0 on 2022-03-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reshuffle', '0006_alter_archivelogs_options_alter_options_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='header',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='parts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
